### ISSUE TITLE
Did I break my 2652 stick?

### ISSUE THREAD

**Issue by TheStigh** [slaesh/cc2652-stick#15]
Did accidentally flash it with the 'other_coordinator' version, now when plugging the adapter, the Green and Orange light are ON. Cannot read the status using the  https://github.com/slaesh/cc2652-stick/tree/master/coordinator-test script. 

I've also tried to use the cc2538-bsl script (which works great on the other adapter) but it only says `ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'`

So, I'm a bit stuck - how can I get this adapter 'back online' ?

**Comment by Vebryn** [comment]
Hi,

I accidently flash ti sniffing fw which actually disable bootloader. I followed https://electrolama.com/radio-docs/advanced/flash-jtag/ to recover my cc2652rb.

Best regards.
