### ISSUE TITLE
GREAT CARE. IS A GOTCHA.

### ISSUE THREAD

**Issue by grumete** [slaesh/cc2652-stick#17]
Be careful, you buy, you pay and they do not deliver nor do they respond to the telegram.
I have been two months since  the payment and I have not received any communication.
![pago](https://user-images.githubusercontent.com/45306591/132337348-76432b08-23a7-45e6-a7ad-4ba66b878ea9.jpg)

**Comment by Vebryn** [comment]
Hi,

My experience was great despite no support on telegram.

I successfully ordered 2 sticks. I live in France. I received an email with a tracking number.

Did you track your shipment ?

Best regards.

**Comment by andreasbrett** [comment]
Well, I did receive my stick but communication is really bad. Can't get the stick to work and still waiting for any reaction via Telegram. Looking at the open issues here doesn't make me feel good either.

@slaesh Where you at? There's lot's of people waiting on feedback here (not to speak of quite a few people on the discord channel of zigbee2mqtt).

**Comment by grumete** [comment]
I reiterate my discomfort.
He is not able to even attempt to deny the evidence.
I have thrown away the money and I have no way of getting it back. Just the kicking.
