### ISSUE TITLE
Stick is not recognized on Windows

### ISSUE THREAD

**Issue by NimKat16** [slaesh/cc2652-stick#19]
Hello there,
I am a total newbie. I got my stick alright after a few weeks during which there was absolute silence. 
Got this because it was recommended by Koen for MQTT. But i cannot get my Windows PC (Yes, Windows PC) to recognize it :( It goes to Device Manager > Other Devices... no Serial port is assigned to it.. so nothing works :( The bad part is not that, it is total lack of response from the seller to email, chat in website and Telegram. Nothig! I gave up on him... Stick might be great, cannot say yet, but a service like this is really not appreciated. At least they should be honest and say that we do not answer anything...

Anyhow I wonder if any of you gurus can help me out... How can i get my Windows to recognize the Stick?
![image](https://user-images.githubusercontent.com/91806336/135768553-7a08ceb6-bd65-4976-bdee-8ecf84fb0edb.png)

Ciao,
Nima

_Update: Just now I stumbled upon following page. and the USB to UART driver solved the problem of stick not being recognized
https://community.home-assistant.io/t/flashing-slaeshs-cc2652rb-on-a-windows-pc/281068
The required driver is
https://www.silabs.com/documents/public/software/CP210x_Universal_Windows_Driver.zip

BUT the coordinator test still doesnot find the stick although it is now available and i can see it listing the ports in PowerShell_

**Comment by NimKat16** [comment]
> 
> can you try this script: https://github.com/slaesh/cc2652-stick/tree/master/coordinator-test

Hello Peter, as I mentioned in the last line of my original post, the 'coordinator test' still does not find the stick. I can find it with a command in PowerShell.

**Comment by ovizii** [comment]
I'm also interested in the solution to this thread. What would this command look like on a windows system where I have the correct drivers and the device is visible in the hardware manager?

`python3 ./test.py -p /dev/ttyUSB0`

![image](https://user-images.githubusercontent.com/837902/173052655-4aad8c62-d96e-4976-8903-3701fd236e99.png)
