### ISSUE TITLE
Weak Signal - even several antenna ( slaesh typ 2 antenna) 

### ISSUE THREAD

**Issue by ruvnax** [slaesh/cc2652-stick#20]
I orderd your sick cc2652rb , but when i tested the stick it has very bad perofomace in tx/rx - after 3 meter line of sight the signal is nearly 0, i cant even reach my router 8 away in the hallway. with my pervios cc stick and teh conbee no issue. tried different channels no better result. any suggestions or do i recived a bad one.

RGDS #

**Comment by grumete** [comment]
GREAT CARE. IS A GOTCHA.
