### ISSUE TITLE
CC2652R  like many other people ordered ????

### ISSUE THREAD

**Issue by PetersPlace** [slaesh/cc2652-stick#6]
Many people ordered a new  stick  last week https://slae.sh/projects/cc2652/ 
Almost everyone paid for it by Paypall but we do not get any conformation about the order status or shipment labels ?

On the tweakers forum https://gathering.tweakers.net/forum/list_message/66428780#66428780   many people are a bit nervous about this. Some opened a case with paypal for refund.

So whats the problem ??

**Comment by rotrials** [comment]
I also have tried to contact him, by mail, telegram messages, telegram call...  I waiting for an answer for 2 weeks. Pretty strange... 
Did anybody reach him?

**Comment by delicon** [comment]
I've also ordered the zigbee stick. I didn't got nothing about shipment.
I've contacted him on Telegram and also on email without success.
I'll probably request a refund on Paypal.

**Comment by djp3k05** [comment]
same here. Ordered 6 days ago. no shipping yet. I got no reply to emails and telegram. He was last seen  "long time ago".
Smell like scam. I will also open a dispute.

**Comment by rotrials** [comment]
Sad. If this really turn out that is a scam, we should report the entire project to GitHub...

**Comment by vortexua** [comment]
I have ordered on Feb 27th and haven't received any information about shipment. Telegram messages and emails are without reply.
At the same time some people here https://gathering.tweakers.net/forum/list_messages/1901662/last reported that shippings have been started. Will wait couple of days and then contact Paypal as well.

**Comment by rotrials** [comment]
@vortexua: finally, some kind of good news. Thanks

**Comment by rotrials** [comment]
I have ordered on Feb 27 - 2021 as well, and still nothing...

**Comment by purche42** [comment]
Same order issue... ordered 2 Sticks a week ago. No reply on telegram and e-mail. I'm not sure why there is no response at all. A status would be fine, even the message is that it takes a week longer. 
No reply is not really good style and repsonse to a community willing to support koenkk and CC2652R Stick development.  

I will wait, if we either get a sign that somebody is there or I will contact Paypal   :(

**Comment by PetersPlace** [comment]
Hi guys,

Today i received emails from Sleash, he had problems with his webshop. This is fixed now, and he is starting to send mail to all people ho ordered something.   Just now i have also received DHL tracking information.

**Comment by barrymossel** [comment]
This is not how you trade paying customers. I hope PayPal will freeze his account because of all the disputes. I just want my money back and will report this fraud everywhere.

**Comment by rotrials** [comment]
Let's say I can understand that he has problems with webshop and email client. But what about **telegram** and **github**? 
It smells like a lie.

@slaesh

**Comment by fuxoft** [comment]
I've made my order yesterday (more than 24 hours ago) and so far there is no communication from slaesh. He does not answer on Telegram (and his status there is shown as "last seen a long time ago") or in email. So I have no way of actually arranging the payment (luckilly, I have selected "Pay later"). Does anyone have any concrete info about what's happening and whether slaesh is alive and communicating? Should I just move on and buy different hardware?

**Comment by slaesh** [comment]
hey y'all :)

sorry for the lack of communication! we had some issues, more insights in our latest mail!
pls also check you spam-folders!!

we are working day and night to get this done asap!
most likely at the end of this week everything will be send out! ;)
currently, time is our most limiting factor.. and answering mails will not do any progress =/

hope you receive your stick soon! ;)
